class Constants {
  static List<String> tunisianGovernorates = [
    'Ariana',
    'Beja',
    'Ben Arous',
    'Bizerte',
    'Gabes',
    'Gafsa',
    'Jendouba',
    'Kairouan',
    'Kasserine',
    'Kebili',
    'Kef',
    'Mahdia',
    'Manouba',
    'Medenine',
    'Monastir',
    'Nabeul',
    'Sfax',
    'Sidi Bouzid',
    'Siliana',
    'Sousse',
    'Tataouine',
    'Tozeur',
    'Tunis',
    'Zaghouan'
  ];
 static const List<String> countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo, Democratic Republic of the',
    'Congo, Republic of the',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor (Timor-Leste)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North',
    'Korea, South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar (Burma)',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City (Holy See)',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe'
  ];
static List<String> carBrands = [
  "Toyota",
  "Honda",
  "Ford",
  "Chevrolet",
  "Nissan",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Volkswagen",
  "Hyundai",
  "Kia",
  "Subaru",
  "Mazda",
  "Jaguar",
  "Land Rover",
  "Porsche",
  "Lexus",
  "Cadillac",
  "Buick",
  "Chrysler",
  "Dodge",
  "Ram",
  "Jeep",
  "Acura",
  "Infiniti",
  "Tesla",
  "Volvo",
  "Lincoln",
  "Genesis",
  "Mitsubishi",
  "Alfa Romeo",
  "Fiat",
  "Ferrari",
  "Lamborghini",
  "McLaren",
  "Aston Martin",
  "Bentley",
  "Rolls-Royce",
  "Pagani",
  "Smart",
  "Saab",
  "Opel",
  "Peugeot",
  "Renault",
  "Seat",
  "Skoda",
  "Mini",
  "Maybach",
];

    static List<String> carEquipmentNames = [
    'Air Conditioning',
    'Bluetooth',
    'Navigation System',
    'Backup Camera',
    'Heated Seats',
    'Sunroof',
    'Cruise Control',
  ];

static List<String> gearBoxTypes = [
    'MANUEL',
    'AUTOMATIC',
  ];

static List<String> carMotors = [
    'Gasoline',
    'Electric',
    'Diesel',
    'Ethanol',
    'CNG_Engine',
    'Rotary_Engine',
    'Hydrogen_Fuel_Cell',
    'PHEV',
    'Series_Hybrid',
    'Parallel_Hybrid',
    
  ];

  static List<String> carTypes = [
        "sedan",
        "crosserover",
        "SUV",
        "Hatchback",
        "Station Wagon",
        "Coupe",
        "Pickup Truck",
        "Van",
        "Sports Cars",
        "MPV",
        "Supercar",
        "Luxury car",
        "Convertible",
        "Muscle cars",
        "Microcar",
        "Camper Van",
        "Mini Truck",
        "Limousine",
        "Truck",
        "Hot Hatch",
        "Ute",
        "Pony car",
        "Grand Tourer",
        "Shooting Brake",
        "Hot Rod",
        "Low Rider",
        "Roadster"
];
 static List<Map<String, dynamic>> carModels = [
     {
    'brand': 'Acura',
    'models': [
      'ILX',
      'MDX',
      'RDX',
      'TLX',
      'NSX',
    ],
  },
  {
    'brand': 'Alfa Romeo',
    'models': [
      'Giulia',
      'Stelvio',
      '4C',
      'Giulietta',
      'MiTo',
    ],
  },
  {
    'brand': 'Aston Martin',
    'models': [
      'DB11',
      'Vantage',
      'DBS Superleggera',
      'Rapide',
      'DBX',
    ],
  },
  {
    'brand': 'Audi',
    'models': [
      'A3',
      'A4',
      'Q5',
      'Q7',
      'A6',
    ],
  },
  {
    'brand': 'Bentley',
    'models': [
      'Continental GT',
      'Bentayga',
      'Flying Spur',
      'Mulsanne',
      'Arnage',
    ],
  },
  {
    'brand': 'BMW',
    'models': [
      '3 Series',
      '5 Series',
      'X3',
      'X5',
      'Z4',
    ],
  },
  {
    'brand': 'Bugatti',
    'models': [
      'Chiron',
      'Veyron',
      'Divo',
      'Centodieci',
      'La Voiture Noire',
    ],
  },
  {
    'brand': 'Buick',
    'models': [
      'Enclave',
      'Encore',
      'Regal',
      'LaCrosse',
      'Verano',
    ],
  },
  {
    'brand': 'Cadillac',
    'models': [
      'Escalade',
      'XT5',
      'CT6',
      'XT4',
      'ATS',
    ],
  },
  {
    'brand': 'Chevrolet',
    'models': [
      'Silverado',
      'Malibu',
      'Equinox',
      'Traverse',
      'Camaro',
    ],
  },
  {
    'brand': 'Chrysler',
    'models': [
      '300',
      'Pacifica',
      'Voyager',
      'Aspen',
      'Crossfire',
    ],
  },
  {
    'brand': 'Citroën',
    'models': [
      'C3',
      'C4',
      'C5 Aircross',
      'Berlingo',
      'C4 Cactus',
    ],
  },
  {
    'brand': 'Dodge',
    'models': [
      'Charger',
      'Challenger',
      'Durango',
      'Journey',
      'Ram',
    ],
  },
  {
    'brand': 'Ferrari',
    'models': [
      '488 GTB',
      'Portofino',
      '812 Superfast',
      'F8 Tributo',
      'SF90 Stradale',
    ],
  },
  {
    'brand': 'Fiat',
    'models': [
      '500',
      '500X',
      'Panda',
      'Tipo',
      '124 Spider',
    ],
  },
  {
    'brand': 'Ford',
    'models': [
      'F-150',
      'Mustang',
      'Explorer',
      'Escape',
      'Focus',
    ],
  },
  {
    'brand': 'Genesis',
    'models': [
      'G70',
      'G80',
      'G90',
      'GV70',
      'GV80',
    ],
  },
  {
    'brand': 'GMC',
    'models': [
      'Sierra',
      'Terrain',
      'Acadia',
      'Canyon',
      'Yukon',
    ],
  },
  {
    'brand': 'Honda',
    'models': [
      'Civic',
      'Accord',
      'CR-V',
      'Pilot',
      'Fit',
    ],
  },
  {
    'brand': 'Hyundai',
    'models': [
      'Elantra',
      'Sonata',
      'Tucson',
      'Santa Fe',
      'Kona',
    ],
  },
  {
    'brand': 'Infiniti',
    'models': [
      'Q50',
      'QX60',
      'QX50',
      'QX80',
      'Q70',
    ],
  },
  {
    'brand': 'Jaguar',
    'models': [
      'XE',
      'XF',
      'F-Pace',
      'E-Pace',
      'I-Pace',
    ],
  },
  {
    'brand': 'Jeep',
    'models': [
      'Wrangler',
      'Cherokee',
      'Grand Cherokee',
      'Renegade',
      'Compass',
    ],
  },
  {
    'brand': 'Kia',
    'models': [
      'Optima',
      'Sorento',
      'Sportage',
      'Forte',
      'Soul',
    ],
  },
  {
    'brand': 'Lamborghini',
    'models': [
      'Huracan',
      'Aventador',
      'Urus',
      'Gallardo',
      'Murcielago',
    ],
  },
  {
    'brand': 'Land Rover',
    'models': [
      'Range Rover',
      'Discovery',
      'Defender',
      'Velar',
      'Evoque',
    ],
  },
  {
    'brand': 'Lexus',
    'models': [
      'RX',
      'ES',
      'NX',
      'LS',
      'UX',
    ],
  },
  {
    'brand': 'Lincoln',
    'models': [
      'Navigator',
      'Aviator',
      'Corsair',
      'MKZ',
      'Continental',
    ],
  },
  {
    'brand': 'Maserati',
    'models': [
      'Ghibli',
      'Levante',
      'Quattroporte',
      'GranTurismo',
      'MC20',
    ],
  },
  {
    'brand': 'Mazda',
    'models': [
      'Mazda3',
      'Mazda6',
      'CX-5',
      'CX-9',
      'MX-5',
    ],
  },
  {
    'brand': 'McLaren',
    'models': [
      '720S',
      '570S',
      '600LT',
      'GT',
      'P1',
    ],
  },
  {
    'brand': 'Mercedes-Benz',
    'models': [
      'C-Class',
      'E-Class',
      'S-Class',
      'GLE',
      'A-Class',
    ],
  },
  {
    'brand': 'Mini',
    'models': [
      'Cooper',
      'Countryman',
      'Clubman',
      'Convertible',
      'Paceman',
    ],
  },
  {
    'brand': 'Mitsubishi',
    'models': [
      'Outlander',
      'Lancer',
      'Eclipse Cross',
      'Mirage',
      'Pajero',
    ],
  },
  {
    'brand': 'Nissan',
    'models': [
      'Altima',
      'Sentra',
      'Rogue',
      'Murano',
      'GT-R',
    ],
  },
  {
    'brand': 'Pagani',
    'models': [
      'Huayra',
      'Zonda',
    ],
  },
  {
    'brand': 'Peugeot',
    'models': [
      '208',
      '308',
      '508',
      '3008',
      '2008',
    ],
  },
  {
    'brand': 'Porsche',
    'models': [
      '911',
      'Cayenne',
      'Macan',
      'Panamera',
      'Taycan',
    ],
  },
  {
    'brand': 'Ram Trucks',
    'models': [
      '1500',
      '2500',
      '3500',
      'ProMaster',
      'Chassis Cab',
    ],
  },
  {
    'brand': 'Rolls-Royce',
    'models': [
      'Phantom',
      'Ghost',
      'Wraith',
      'Dawn',
      'Cullinan',
    ],
  },
  {
    'brand': 'Subaru',
    'models': [
      'Impreza',
      'Outback',
      'Forester',
      'Crosstrek',
      'Legacy',
    ],
  },
  {
    'brand': 'Suzuki',
    'models': [
      'Swift',
      'Vitara',
      'Jimny',
      'Baleno',
      'Celerio',
    ],
  },
  {
    'brand': 'Tesla',
    'models': [
      'Model S',
      'Model 3',
      'Model X',
      'Model Y',
      'Cybertruck',
    ],
  },
  {
    'brand': 'Toyota',
    'models': [
      'Camry',
      'Corolla',
      'RAV4',
      'Prius',
      'Land Cruiser',
    ],
  },
  {
    'brand': 'Volkswagen',
    'models': [
      'Golf',
      'Passat',
      'Tiguan',
      'Atlas',
      'Jetta',
    ],
  },
  {
    'brand': 'Volvo',
    'models': [
      'XC90',
      'XC60',
      'S60',
      'V60',
      'S90',
    ],
  },
];



  static String ModeProprietaire = "RENTER" ; 
    static String ModeLocataire = "CUSTOMER" ; 
}
